/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 04-apr-2022 23:49:09 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Riik" CASCADE
;

DROP TABLE IF EXISTS "Tootaja_roll" CASCADE
;

DROP TABLE IF EXISTS "Tootaja_seisundi_liik" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkti_seisundi_liik" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkti_kategooria_tyyp" CASCADE
;

DROP TABLE IF EXISTS "Kliendi_seisundi_liik" CASCADE
;

DROP TABLE IF EXISTS "Isiku_seisundi_liik" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkti_tyyp" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkti_kategooria" CASCADE
;

DROP TABLE IF EXISTS "Isik" CASCADE
;

DROP TABLE IF EXISTS "Kasutajakonto" CASCADE
;

DROP TABLE IF EXISTS "Tootaja" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkt" CASCADE
;

DROP TABLE IF EXISTS "Klient" CASCADE
;

DROP TABLE IF EXISTS "Laadimispunkti_kategooria_omamine" CASCADE
;

DROP TABLE IF EXISTS "Tootaja_rolli_omamine" CASCADE
;

/* Create Tables */

CREATE TABLE "Riik"
(
	"kood" char(3)	 NOT NULL,
	"nimetus" char(50)	 NOT NULL,
	CONSTRAINT "PK_Riik" PRIMARY KEY ("kood")
)
;

CREATE TABLE "Tootaja_roll"
(
	"kirjeldus" char(1)	 NULL,
	"kood" char(1)	 NOT NULL,
	"nimetus" char(1)	 NOT NULL,
	CONSTRAINT "PK_Tootaja_roll" PRIMARY KEY ("kood")
)
;

CREATE TABLE "Tootaja_seisundi_liik"
(
	"kood" char(1)	 NOT NULL,
	"nimetus" char(1)	 NOT NULL,
	CONSTRAINT "PK_Tootaja_seisundi_liik" PRIMARY KEY ("kood")
)
;

CREATE TABLE "Laadimispunkti_seisundi_liik"
(
	"kood" char(50)	 NOT NULL,
	"nimetus" char(50)	 NOT NULL,
	CONSTRAINT "PK_Laadimispunkti_seisundi_liik" PRIMARY KEY ("kood")
)
;

CREATE TABLE "Laadimispunkti_kategooria_tyyp"
(
	"kategooria_kood" char(50)	 NOT NULL,
	"nimetus" char(50)	 NOT NULL,
	CONSTRAINT "PK_Laadimispunkti_kategooria_tyyp" PRIMARY KEY ("kategooria_kood")
)
;

CREATE TABLE "Kliendi_seisundi_liik"
(
	"kood" char(1)	 NOT NULL,
	"nimetus" char(1)	 NOT NULL,
	CONSTRAINT "PK_Kliendi_seisundi_liik" PRIMARY KEY ("kood")
)
;

CREATE TABLE "Isiku_seisundi_liik"
(
	"kood" char(1)	 NOT NULL,
	"nimetus" char(1)	 NOT NULL,
	CONSTRAINT "PK_Isiku_seisundi_liik" PRIMARY KEY ("kood")
)
;

CREATE TABLE "Laadimispunkti_tyyp"
(
	"kiirlaadimine" boolean NOT NULL,
	"kood" char(50)	 NOT NULL,
	"laadimispunkti_tyyp_id" integer NOT NULL,
	CONSTRAINT "PK_Laadimispunkti_tyyp" PRIMARY KEY ("laadimispunkti_tyyp_id"),
	CONSTRAINT "FK_Laadimispunkti_tyyp_Riik" FOREIGN KEY ("kood") REFERENCES "Riik" ("kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Laadimispunkti_tyyp_Tootaja_roll" FOREIGN KEY ("kood") REFERENCES "Tootaja_roll" ("kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Laadimispunkti_tyyp_Tootaja_seisundi_liik" FOREIGN KEY ("kood") REFERENCES "Tootaja_seisundi_liik" ("kood") ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE "Laadimispunkti_kategooria"
(
	"kood" char(50)	 NOT NULL,
	"nimetus" char(50)	 NOT NULL,
	"kategooria_kood" char(50)	 NOT NULL,
	CONSTRAINT "PK_Laadimispunkti_kategooria" PRIMARY KEY ("kategooria_kood"),
	CONSTRAINT "FK_Laadimispunkti_kategooria_Laadimispunkti_kategooria_tyyp" FOREIGN KEY ("kategooria_kood") REFERENCES "Laadimispunkti_kategooria_tyyp" ("kategooria_kood") ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE "Isik"
(
	"isik_id" bigint NOT NULL,
	"isikukood" char(50)	 NOT NULL,
	"isikukoodi_riik" char(3)	 NOT NULL,
	"e_meil" char(254)	 NOT NULL,
	"synni_kp" date NOT NULL,
	"reg_aeg" timestamp(6) with time zone NOT NULL DEFAULT LOCALTIMESTAMP,
	"eesnimi" char(1000)	 NULL,
	"perenimi" char(1000)	 NULL,
	"elukoht" char(1000)	 NULL,
	"isiku_seisundi_liik_kood" char(50)	 NOT NULL,
	CONSTRAINT "PK_Isik" PRIMARY KEY ("isik_id"),
	CONSTRAINT "AK_isik_isikukood_isikukoodi_riik" UNIQUE ("isikukood","isikukoodi_riik"),
	CONSTRAINT "AK_isik_e_meil" UNIQUE ("e_meil"),
	CONSTRAINT "FK_isikukoodi_riik" FOREIGN KEY ("isikukoodi_riik") REFERENCES "Riik" ("kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Isik_Isiku_seisundi_liik" FOREIGN KEY ("isiku_seisundi_liik_kood") REFERENCES "Isiku_seisundi_liik" ("kood") ON DELETE No Action ON UPDATE Cascade
)
;

CREATE TABLE "Kasutajakonto"
(
	"isik_id" bigint NOT NULL,
	"on_aktiivne" boolean NOT NULL DEFAULT TRUE,
	"parool" char(50)	 NOT NULL,
	CONSTRAINT "PK_Kasutajakonto" PRIMARY KEY ("isik_id"),
	CONSTRAINT "FK_Kasutajakonto_Isik" FOREIGN KEY ("isik_id") REFERENCES "Isik" ("isik_id") ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE "Tootaja"
(
	"kood" char(50)	 NOT NULL,
	"isik_id" bigint NOT NULL,
	CONSTRAINT "PK_Tootaja" PRIMARY KEY ("isik_id"),
	CONSTRAINT "FK_Tootaja_Tootaja_seisundi_liik" FOREIGN KEY ("kood") REFERENCES "Tootaja_seisundi_liik" ("kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Tootaja_Isik" FOREIGN KEY ("isik_id") REFERENCES "Isik" ("isik_id") ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE "Laadimispunkt"
(
	"asukoht" char(50)	 NOT NULL,
	"laadimiskordade_arv" integer NOT NULL,
	"Laadimispunkti_kood" integer NOT NULL,
	"nimetus" char(50)	 NOT NULL,
	"reg_aeg" timestamp(6)	 NOT NULL,
	"registreerija_id" bigint NOT NULL,
	"kood" char(50)	 NOT NULL,
	"laadimispunkti_tyyp_id" integer NOT NULL,
	CONSTRAINT "PK_Laadimispunkt" PRIMARY KEY ("Laadimispunkti_kood"),
	CONSTRAINT "FK_Laadimispunkt_Laadimispunkti_seisundi_liik" FOREIGN KEY ("kood") REFERENCES "Laadimispunkti_seisundi_liik" ("kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Laadimispunkt_Laadimispunkti_tyyp" FOREIGN KEY ("laadimispunkti_tyyp_id") REFERENCES "Laadimispunkti_tyyp" ("laadimispunkti_tyyp_id") ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT "FK_Laadimispunkt_Tootaja" FOREIGN KEY ("registreerija_id") REFERENCES "Tootaja" ("isik_id") ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE "Klient"
(
	"on_nous_tylitamisega" boolean NOT NULL,
	"isik_id" bigint NOT NULL,
	"kood" char(1)	 NOT NULL,
	CONSTRAINT "PK_Klient" PRIMARY KEY ("isik_id"),
	CONSTRAINT "FK_Klient_Kliendi_seisundi_liik" FOREIGN KEY ("kood") REFERENCES "Kliendi_seisundi_liik" ("kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Klient_Isik" FOREIGN KEY ("isik_id") REFERENCES "Isik" ("isik_id") ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE "Laadimispunkti_kategooria_omamine"
(
	"Laadimispunkti_kood" integer NOT NULL,
	"kood" char(50)	 NOT NULL,
	CONSTRAINT "PK_Laadimispunkti_kategooria_omamine" PRIMARY KEY ("Laadimispunkti_kood","kood"),
	CONSTRAINT "FK_Laadimispunkti_kategooria_omamine_Laadimispunkt" FOREIGN KEY ("Laadimispunkti_kood") REFERENCES "Laadimispunkt" ("Laadimispunkti_kood") ON DELETE No Action ON UPDATE No Action
)
;

CREATE TABLE "Tootaja_rolli_omamine"
(
	"alguse_aeg" date NOT NULL,
	"lopu_aeg" date NULL,
	"kood" char(1)	 NOT NULL,
	"isik_id" bigint NOT NULL,
	"tootaja_rolli_omamine_id" integer NOT NULL,
	CONSTRAINT "PK_Tootaja_rolli_omamine" PRIMARY KEY ("tootaja_rolli_omamine_id"),
	CONSTRAINT "FK_Tootaja_rolli_omamine_Tootaja_roll" FOREIGN KEY ("kood") REFERENCES "Tootaja_roll" ("kood") ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT "FK_Tootaja_rolli_omamine_Tootaja" FOREIGN KEY ("isik_id") REFERENCES "Tootaja" ("isik_id") ON DELETE No Action ON UPDATE No Action
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE "Laadimispunkt"
	IS 'Vaja nimetusele panna unique kitsendus.  ? Kas on vaja lisada klassifikaatorit ?'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

CREATE INDEX "IXFK_Laadimispunkti_kategooria_Laadimispunkti_kategooria_tyyp" ON "Laadimispunkti_kategooria" ("kategooria_kood" ASC)
;

CREATE INDEX "IXFK_isikukoodi_riik" ON "Isik" ("isikukoodi_riik" ASC)
;

CREATE INDEX "IXFK_Laadimispunkt_Tootaja" ON "Laadimispunkt" ("registreerija_id" ASC)
;

CREATE INDEX "IXFK_Laadimispunkti_kategooria_omamine_Laadimispunkt" ON "Laadimispunkti_kategooria_omamine" ("Laadimispunkti_kood" ASC)
;
